server:
  port: 8100

spring:
  application:
    name: hycloud-demo
  datasource:
    url: jdbc:mysql://192.168.99.200:3306/hycloud
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.99.200
    port: 6379
    database: 1
    timeout: 3000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

security:
  oauth2:
    resource:
      filter-order: 3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/