server:
  port: 9050

spring:
  application:
    name: zipkin-server

management:
  metrics:
    web:
      server:
        auto-time-requests: false

zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.99.200:5672
      username: admin
      password: 123456
      queue: zipkin

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug