server:
  port: 80

spring:
  application:
    name: hycloud-zuul
  profiles:
    active: dev

zuul:
  sensitive-headers:
    ribbon:
      eager-load:
        enable: true
  routes:
    hycloud-sso: /auth/**
    hycloud-demo: /demo/**

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix.command.default.execution:
  # isolation.thread.timeoutInMilliseconds: 10000
  timeout.enabled: false

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

